# Generated by Django 5.1.4 on 2025-01-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
