# Generated by Django 5.1.4 on 2025-01-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_item_description_alter_place_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplacement',
            name='role',
        ),
    ]
